export const ERROR_OUTPUT_TYPE = 'ERROR_OUTPUT';
export const TEXT_OUTPUT_TYPE = 'TEXT_OUTPUT';
export const PROMPT_OUTPUT_TYPE = 'PROMPT_OUTPUT'
export const WARNING_OUTPUT_TYPE = 'WARNING_OUTPUT';
export const INFO_OUTPUT_TYPE = 'INFO_OUTPUT';
